# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # - board: nice_nano_v2
  #   shield: sofle_ergomech_left
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y
  # - board: nice_nano_v2
  #   shield: sofle_ergomech_right
  # - board: nice_nano_v2
  #   shield: settings_reset



include:
  - board: nice_nano_v2
    shield: sofle_ergomech_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: sofle_ergomech_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  
  # New dongle configuration (can use any BLE-capable board)
  - board: seeeduino_xiao_ble
    shield: sofle_ergomech_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  
  # Settings reset for all devices
  - board: nice_nano_v2
    shield: settings_reset