# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    #shield: sofle_ergomech_left nice_oled  # for oled
    #shield: sofle_ergomech_left nice_view_adapter nice_epaper  #for nice!view mctechnology17/zmk-nice-oled
    shield: sofle_ergomech_left nice_view_adapter  nice_view  #for nice!view Crimsonmars/hammerbeam-slideshow
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    #uncomment if u want zmk studio unlocked by default
    #cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano_v2
    #shield: sofle_ergomech_right nice_oled  # for oled
    #shield: sofle_ergomech_right nice_view_adapter nice_epaper  #for nice!view mctechnology17/zmk-nice-oled
    shield: sofle_ergomech_right nice_view_adapter nice_view_custom #for nice!view Crimsonmars/hammerbeam-slideshow
  - board: nice_nano_v2
    shield: settings_reset
